
import { Injectable } from '@angular/core';

export interface PortfolioItem {
  title: string;
  description: string;
  imageUrl: string;
  projectUrl: string;
  category: 'Website' | 'Mobile App' | 'Dashboard' | 'Design' | 'Live Project' | 'Figma';
}

@Injectable({
  providedIn: 'root'
})
export class PortfolioDataService {
  private projects: PortfolioItem[] = [
    // Live Projects
    { title: 'Tata Steel Nexus (UK - Live)', description: 'A live B2B eCommerce platform for Tata Steel UK, providing advanced services and a seamless purchasing experience for industrial clients.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.tatasteeluk.com/services/nexus')}?w=600&h=400`, projectUrl: 'https://www.tatasteeluk.com/services/nexus', category: 'Live Project' },
    { title: 'Tata Steel Nexus (Europe - Live)', description: 'The live B2B eCommerce portal for Tata Steel Europe, offering services and products to a continental market with a focus on usability.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://products.tatasteelnederland.com/services/nexus')}?w=600&h=400`, projectUrl: 'https://products.tatasteelnederland.com/services/nexus', category: 'Live Project' },
    { title: 'NextEra 360 Dashboard (Live)', description: 'A B2C energy dashboard for NextEra Energies, giving customers powerful insights and control over their energy consumption.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.nexteraenergyresources.com/nextera360/our-company/wizard.html')}?w=600&h=400`, projectUrl: 'https://www.nexteraenergyresources.com/nextera360/our-company/wizard.html', category: 'Live Project' },
    
    // Figma Prototypes & Designs
    { title: 'Figma AI Event Planner', description: 'An AI-based event planner concept designed in Figma, featuring a sleek dark mode interface to streamline event organization.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.figma.com/make/BAtL63MQYpjJfb6j9Gprhb/Dark-UpGenie-AI-Platform?t=U5tYmlKHdf7RiRer&fullscreen=1')}?w=600&h=400`, projectUrl: 'https://www.figma.com/make/BAtL63MQYpjJfb6j9Gprhb/Dark-UpGenie-AI-Platform?t=U5tYmlKHdf7RiRer&fullscreen=1', category: 'Figma' },
    { title: 'Figma Rabobank Interactive Dashboard', description: 'An interactive dashboard prototype for Rabobank, created in Figma to showcase data visualization and key financial metrics.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.figma.com/make/TIAhiT4mTWbA29uyGpeTyt/Rabobank-Interactive-Dashboard?node-id=0-1&p=f&fullscreen=1')}?w=600&h=400`, projectUrl: 'https://www.figma.com/make/TIAhiT4mTWbA29uyGpeTyt/Rabobank-Interactive-Dashboard?node-id=0-1&p=f&fullscreen=1', category: 'Figma' },
    { title: 'Figma Fly Easy Assistance Prototype', description: 'A high-fidelity prototype of the Fly Easy airport assistance app, created in Figma to demonstrate user flows and interactive elements.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.figma.com/proto/DVjJ2AXnypfIgLMWEkVDVZ/FlyApp?node-id=10-280&starting-point-node-id=2%3A2&t=1KwSf54xPPPOA2Gs-1')}?w=600&h=400`, projectUrl: 'https://www.figma.com/proto/DVjJ2AXnypfIgLMWEkVDVZ/FlyApp?node-id=10-280&starting-point-node-id=2%3A2&t=1KwSf54xPPPOA2Gs-1', category: 'Figma' },

    // Mobile Apps
    { title: 'Fly Easy Airport Assistance', description: 'A user-centric app designed to provide seamless assistance and services within airports, making travel easier and more enjoyable for everyone.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/238839733/User-centric-app-for-easy-airport-services-assistance')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/238839733/User-centric-app-for-easy-airport-services-assistance', category: 'Mobile App' },
    { title: 'Rabobank Privilege Banking App', description: 'A modernization project for an MNC financial bank, enhancing the premium customer experience for their privilege banking clients.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/235968269/MNC-Financial-Bank-App-Modernization')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/235968269/MNC-Financial-Bank-App-Modernization', category: 'Mobile App' },
    { title: 'Tata Steel Europe SOS App', description: 'A critical outage reporting application for a major steel manufacturer, ensuring rapid response and minimizing downtime during emergencies.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/235965217/MNC-Steel-Manufacturer-Critical-Outage-Application')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/235965217/MNC-Steel-Manufacturer-Critical-Outage-Application', category: 'Mobile App' },
    { title: 'Woobabble Dating App', description: 'A location-based dating application connecting local singles with a fun and intuitive UI to foster meaningful connections.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/52957571/Woobabble-is-a-location-based-dating-application')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/52957571/Woobabble-is-a-location-based-dating-application', category: 'Mobile App' },
    { title: 'Cabber Taxi Booking App', description: 'A sleek and efficient cab booking application for seamless local travel and transportation, designed for ease of use and reliability.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/52856529/Cabber-Taxi-Booking-App')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/52856529/Cabber-Taxi-Booking-App', category: 'Mobile App' },
    { title: 'QlikChain Property Search App', description: 'A blockchain-based property search application that ensures transparent and secure real estate transactions, enhancing trust for buyers and sellers.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/237770831/QlikChain-Properties')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/237770831/QlikChain-Properties', category: 'Mobile App' },
    { title: 'ImCelebrity App', description: 'A unique mobile application connecting fans with their favorite celebrities through exclusive content and interactive experiences.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/237769699/ImCelebrity-App')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/237769699/ImCelebrity-App', category: 'Mobile App' },
    { title: 'MakeMyTrip App Redesign Ideation', description: 'A personal redesign concept for the MakeMyTrip app, exploring new ideas to enhance usability and create a more delightful travel booking experience.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/235963919/MMT-Personal-Redesign-Ideation')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/235963919/MMT-Personal-Redesign-Ideation', category: 'Mobile App' },
    { title: 'AvFuzon iOS Video Editing App', description: 'AVFuzon is a sleek video editing application for iOS, designed to provide powerful tools in a simple, intuitive user interface for creators on the go.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/53024623/AVFuzon-It-is-a-video-editing-iOS-application')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/53024623/AVFuzon-It-is-a-video-editing-iOS-application', category: 'Mobile App' },

    // Dashboards
    { title: 'Lipton Tea Quality Intelligence', description: 'A blockchain-powered solution for tracking tea quality and ensuring supply chain transparency from the plantation to your cup.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/238795019/Blockchain-Powered-Tea-Quality-Intelligence')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/238795019/Blockchain-Powered-Tea-Quality-Intelligence', category: 'Dashboard' },
    { title: 'Rabobank Financial Audit Dashboard', description: 'An intuitive interface for auditing financial bank transactions with powerful data visualization, simplifying complex data analysis for auditors.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/235967683/MNC-Financial-Bank-Transaction-Audit-Interface')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/235967683/MNC-Financial-Bank-Transaction-Audit-Interface', category: 'Dashboard' },
    { title: 'Rabobank Commission Dashboard', description: 'An agent commission dashboard for a multinational bank, designed to provide clear, actionable insights into sales performance and earnings.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/235967457/MNC-Financial-Banking-Agent-Commission-Dashboard')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/235967457/MNC-Financial-Banking-Agent-Commission-Dashboard', category: 'Dashboard' },
    { title: 'Tata Steel Europe Worker Dashboard', description: 'A worker-focused dashboard for a steel manufacturer, providing essential information, safety alerts, and task management in an industrial setting.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/235964541/MNC-Steel-Manufacturer-Worker-Dashboard')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/235964541/MNC-Steel-Manufacturer-Worker-Dashboard', category: 'Dashboard' },
    
    // Websites
    { title: 'Combat Academy', description: 'A premier platform for combat sport activities, connecting enthusiasts with trainers and events for a seamless booking and community experience.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/238842867/A-premier-platform-for-combat-sport-activities')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/238842867/A-premier-platform-for-combat-sport-activities', category: 'Website' },
    { title: 'TalentChain', description: 'A blockchain project focused on verifying skills and creating a transparent talent marketplace, connecting employers with qualified candidates.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/237770491/TalentChain-Blockchain-project')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/237770491/TalentChain-Blockchain-project', category: 'Website' },
    { title: 'Tata Steel Europe Landing Page', description: 'A global landing page design for a multinational steel manufacturer, focusing on corporate identity and showcasing their global presence.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/235965083/MNC-Steel-Manufacturer-Global-Landing-Page-Design')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/235965083/MNC-Steel-Manufacturer-Global-Landing-Page-Design', category: 'Website' },
    { title: 'GitHub Profile', description: 'A collection of personal and professional coding projects, demonstrating technical skills and contributions to various repositories.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://github.com/rddesigner')}?w=600&h=400`, projectUrl: 'https://github.com/rddesigner', category: 'Website' },

    // Design (UX, UI, General)
    { title: 'Tata Steel User Flow Journey Map', description: 'A comprehensive user flow and journey mapping project for an MNC steel manufacturer to optimize the digital customer experience.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/235964873/MNC-Steel-Manufacturer-User-Flow-Expereince')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/235964873/MNC-Steel-Manufacturer-User-Flow-Expereince', category: 'Design' },
    { title: 'Email Template Design', description: 'A visually appealing email template designed for marketing campaigns, focusing on clear communication and brand consistency to engage subscribers effectively.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/237771069/Email-Template')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/237771069/Email-Template', category: 'Design' },
    { title: 'Company Logo Designs', description: 'A collection of logos designed for various companies, capturing brand identity and values through creative and memorable visual marks.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://www.behance.net/gallery/60168993/Logo-Design')}?w=600&h=400`, projectUrl: 'https://www.behance.net/gallery/60168993/Logo-Design', category: 'Design' },
    { title: 'Creative Work Gallery', description: 'A personal gallery showcasing creative works, including poetry, crafts, DIY projects, decor, photography, and Mandala art.', imageUrl: `https://s.wordpress.com/mshots/v1/${encodeURIComponent('https://ritawebdesigner.wordpress.com/creative-gallery/')}?w=600&h=400`, projectUrl: 'https://ritawebdesigner.wordpress.com/creative-gallery/', category: 'Design' },
  ];

  getProjects(): PortfolioItem[] {
    return this.projects;
  }
}
